version: "3.8"

services:
  encurtador:
    image: murilonerdx/encurtador
    ports:
      - "8099:8099"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
    networks:
      - services
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.ms-encurtador.rule=Host(``)
        - traefik.http.routers.ms-encurtador.entrypoints=websecure
        - traefik.http.routers.ms-encurtador.tls.certresolver=le
        - traefik.http.services.ms-encurtador.loadbalancer.server.port=8099
networks:
  services:
    external: true
  traefik_public:
    external: true
